# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
	['app_launcher.py'],
	pathex=[],
	binaries=[],
	datas=[
		('streamlit_app.py', '.'),
		('templates/*', 'templates'),
		('form_rpa', 'form_rpa'),
		('sample_leads.csv', '.'),
		('challenge.xlsx', '.'),
		('問い合わせ営業　打合せ用.csv', '.'),
	],
	hiddenimports=[
		'streamlit',
		'streamlit.web',
		'streamlit.web.cli',
		'streamlit.runtime',
		'streamlit.runtime.scriptrunner',
		'streamlit.runtime.state',
		'pandas',
		'selenium',
		'selenium.webdriver',
		'selenium.webdriver.chrome',
		'selenium.webdriver.firefox',
		'selenium.webdriver.common',
		'webdriver_manager',
		'webdriver_manager.chrome',
		'webdriver_manager.firefox',
		'jinja2',
		'openpyxl',
		'openai',
		'dotenv',
		'tenacity',
		'pydantic',
		'python-dateutil',
		'requests',
		'urllib3',
		'certifi',
		'charset_normalizer',
		'form_rpa',
		'form_rpa.runner',
		'form_rpa.browser',
		'form_rpa.form_filler',
		'form_rpa.lead_loader',
		'form_rpa.template_engine',
		'form_rpa.ai_assist',
		'form_rpa.captcha',
		'form_rpa.cli',
		'form_rpa.logging_utils',
		'form_rpa.quota',
	],
	hookspath=[],
	runtime_hooks=[],
	excludes=[],
	cipher=block_cipher,
	noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
	pyz,
	a.scripts,
	a.binaries,
	a.zipfiles,
	a.datas,
	name='WebFormRPA',
	debug=False,
	strip=False,
	upx=True,
	console=True,
	disable_windowed_traceback=False,
	target_arch=None,
)
