name: Build Desktop Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build
        run: |
          pyinstaller pyinstaller.spec --clean --noconfirm
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebFormRPA-${{ matrix.os }}
          path: dist/**
